#!/bin/bash

# Source the colors file
source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar
sketchybar --bar position=top height=40 blur_radius=30 color=$BAR_COLOR padding_left=10 padding_right=10

##### Changing Defaults #####
# Default values applied to all further items
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=30
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Add mission control spaces
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=7
    icon.padding_right=7
    background.color=$ITEM_BG_COLOR
    background.corner_radius=5
    background.height=25
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid 2>/dev/null || skhd -k \"ctrl - $sid\""
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
# Add items to the left side of the bar
sketchybar --add item front_app left \
           --set front_app icon.drawing=off \
                          script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# Add items to the right side of the bar
sketchybar --add item clock right \
           --set clock update_freq=10 \
                      icon=󱑍 \
                      script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 \
                        script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update