# version: 1.0.0

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000
scan_timeout = 30
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
($nix_shell$container$fill$git_metrics\n)\
$cmd_duration\
$hostname\
$localip\
$shlvl\
$os\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$typst\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$bun\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$battery"""

[os]
format = "[$symbol](bold fg:#7aa2f7)"
style = "bold fg:#7aa2f7"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[❯](bold italic bright-yellow)"
error_symbol = "[✗](bold italic red)"
vimcmd_symbol = "[❮](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "󰈈"

[shell]
disabled = false
bash_indicator = ""
zsh_indicator = ""
unknown_indicator = "󰞷 "
style = "bold italic blue"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[env_var.CLAUDE_CODE_ENTRYPOINT]
variable = "CLAUDE_CODE_ENTRYPOINT"
format = "[ ](bold italic bright-cyan)"
style = "bold italic bright-cyan"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "󰋄 "
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[󰀄 $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = ""
truncation_length = 2
truncation_symbol = " "
read_only = " 󰌾"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [󰘬](bold bright-blue)'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[cmd_duration]
format = "[󱦟 $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[󰜎](blue italic)"

[localip]
ssh_only = true
format = " 󰩟[$localipv4](bold magenta)"
disabled = false

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "󰁹"
charging_symbol = "[󰂄](italic bold green)"
discharging_symbol = "󰂃"
unknown_symbol = "󰂑"
empty_symbol = "󰂎"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[kubernetes]
disabled = false
detect_files = ["k8s", "Chart.yaml", "helmfile.yaml", "kustomization.yaml"]
detect_folders = ["k8s", "kube", "helm", "charts"]
detect_extensions = []
format = ' [$symbol$context⎪$namespace](bold purple)'
symbol = "☸ "

[kubernetes.context_aliases]
"prod-cluster" = "🔴 prod"
"dev-cluster" = "🟢 dev"
"staging-cluster" = "🟡 stage"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "󰘬 "
style = "italic bright-blue"
truncation_symbol = "…"
truncation_length = 11
only_attached = true

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[󰞇](italic bright-magenta)"
ahead = "[⇡${count}](italic green)"
behind = "[⇣${count}](italic red)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](italic bright-magenta)"
untracked = "[?](italic bright-yellow)"
stashed = "[󰜦](italic white)"
modified = "[!](italic yellow)"
staged = "[+${count}](italic bright-cyan)"
renamed = "[󰁕](italic bright-blue)"
deleted = "[✘](italic red)"

[git_state]
format = "[$state]($style) "
style = "italic dimmed yellow"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"

[deno]
format = " [deno](italic) [🦕 $version](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "󰢱 "
style = "bold bright-yellow"

[nodejs]
format = " [node](italic) [󰎙 ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = [
  "package.json",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
]
detect_folders = ["node_modules"]
detect_extensions = ["js", "mjs", "cjs", "ts"]

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "󰌠 "
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = "󰴭 "
version_format = "${raw}"
style = "bold red"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "󱘗 "
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "󰏗 "
style = "dimmed yellow italic bold"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = "󰛥 "
style = "bold bright-red"
version_format = "${raw}"

[bun]
format = " [bun](italic) [${symbol}${version}]($style)"
symbol = "󰳮 "
style = "bold yellow"
version_format = "${raw}"

[typst]
format = " [typst](italic) [${symbol}${version}]($style)"
symbol = "󰛦 "
style = "bold blue"
version_format = "${raw}"
detect_extensions = ["typ"]
detect_files = ["typst.toml"]

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = "󰸏 "

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\))]($style)'
symbol = "☁️"
style = "bold blue"

[buf]
symbol = "󰛦 "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = "󰙱 "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = "󰔶 "
format = " conda [$symbol$environment]($style)"

[dart]
symbol = "󰘨 "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = "󰡨 "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = "󰴹 "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = "󰻫 "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = "󰟓 "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = "󰲒 "
format = " hs [$symbol($version )]($style)"

[java]
symbol = "󰬷 "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = "󰣐 "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = "󰆥 "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = '🐚'
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed yellow)'

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"


