[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
primary = { background = "#0a0a0d", foreground = "#787c99" }
cursor = { text = "#1a1b26", cursor = "#c0caf5" }
normal = { black = "#363b54", red = "#f7768e", green = "#41a6b5", yellow = "#e0af68", blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#787c99" }
bright = { black = "#363b54", red = "#f7768e", green = "#41a6b5", yellow = "#e0af68", blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#acb0d0" }
dim = { black = "#363b54", red = "#f7768e", green = "#41a6b5", yellow = "#e0af68", blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#787c99" }

[colors.search.focused_match]
background = "#3d59a1"
foreground = "#ffffff"

[colors.search.matches]
background = "#3d59a1"
foreground = "#ffffff"

[colors.hints.start]
background = "#e0af68"
foreground = "#1a1b26"

[colors.hints.end]
background = "#3d59a1"
foreground = "#ffffff"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "#515c7e"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[cursor]
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Block"
[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16.0
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[general]
live_config_reload = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Command|Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[terminal]

[mouse]
hide_when_typing = true
[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.8
decorations = "buttonless"
dynamic_padding = true
blur = true
startup_mode = "windowed"
option_as_alt = 'Both'

[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 10
y = 10

[keyboard]
